// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // We apply "as any" right here to satisfy the tight type definitions
    // while feeding the direct connection parameter to Prisma's engine layers.
    directUrl: process.env["DIRECT_URL"],
  } as any,
});
